/*
 * Candy Server
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

 import (
	 "crypto/tls"
	 "crypto/x509"
	 "fmt"
	 "io/ioutil"
	 "net/http"
	 "os"
 )
 
 func main() {
	 server := getServer()
	 http.HandleFunc("/buy_candy", BuyCandy)
	 must(server.ListenAndServeTLS("", ""))
 }
 
 func getServer() *http.Server {
	 cp := x509.NewCertPool()
	 data, _ := ioutil.ReadFile("../minica.pem")
	 cp.AppendCertsFromPEM(data)
 
	 // c, _ := tls.LoadX509KeyPair("cert.pem", "key.pem")
 
	 tls := &tls.Config{
		 // Certificates:          []tls.Certificate{c},
		 ClientCAs:             cp,
		 ClientAuth:            tls.RequireAndVerifyClientCert,
		 GetCertificate:        CertReqFunc("cert.pem", "key.pem"),
		 VerifyPeerCertificate: CertificateChains,
	 }
 
	 server := &http.Server{
		 Addr:      ":3333",
		 TLSConfig: tls,
	 }
	 return server
 }
 
 func must(err error) {
	 if err != nil {
		 fmt.Printf("Server error: %v\n", err)
		 os.Exit(1)
	 }
 }